import path from 'path'
import esbuild from 'esbuild'
import process from 'process'
import { builtinModules } from 'module'
import fs from 'fs'

// Node builtins we want bundled (with browser-compatible polyfills) instead of
// left as external `require()` calls — so the plugin works on Obsidian mobile
// where the JS runtime has no Node module resolver.
const polyfilledBuiltins = new Set(['events'])
const nodeBuiltins = [
  ...builtinModules,
  ...builtinModules.map((mod) => `node:${mod}`),
].filter((m) => !polyfilledBuiltins.has(m) && !polyfilledBuiltins.has(m.replace(/^node:/, '')))

/**
 * Plugin to make pglite's IN_NODE check evaluate to false.
 * pglite checks if it's running in node by evaluating
 * ```ts
 *   typeof process === 'object' &&
 *   typeof process.versions === 'object' &&
 *   typeof process.versions.node === 'string'
 * ```
 * This plugin injects an empty process object at the top of pglite files.
 * 
 * @see https://github.com/electric-sql/pglite/blob/fea963739ccf08ef546265fa3e401bf93f53e81a/packages/pglite/src/utils.ts#L6-L9
 */
const pgliteShimPlugin = {
  name: 'pglite-shim-plugin',
  setup(build) {
    build.onLoad({ filter: /@electric-sql\/pglite/ }, async (args) => {
      const source = await fs.promises.readFile(args.path, 'utf8')
      const shimSource = `const process = {};\n${source}`
      return { contents: shimSource, loader: 'js' }
    })
  },
}


const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
version: 1.4.5
*/
// --- Mobile-safe runtime shims --------------------------------------------
// Obsidian on iOS/Android has no Node.js \`require\` for fs/child_process/etc.
// Some dependencies still call \`require("os")\` or read \`process.cwd\` at module
// top-level. We polyfill \`process\` and wrap \`require\` so unresolvable node
// builtins return an empty proxy instead of throwing.
if (typeof globalThis.process === 'undefined') {
  globalThis.process = { env: {}, platform: 'web', versions: {}, cwd: function(){return '/'} };
}
if (typeof require !== 'undefined') {
  var __origRequire = require;
  // eslint-disable-next-line no-global-assign
  require = function(id) {
    try { return __origRequire(id); }
    catch (e) { return new Proxy({}, { get: function(){ return undefined; } }); }
  };
  Object.assign(require, __origRequire);
}
// --------------------------------------------------------------------------
`

const prod = process.argv[2] === 'production'

// Redirect bare 'lucide-react' imports to our curated icon barrel (exact match only,
// so 'lucide-react/dist/esm/icons/...' sub-paths in the barrel itself are unaffected)
const lucideIconsPlugin = {
  name: 'lucide-icons-barrel',
  setup(build) {
    build.onResolve({ filter: /^lucide-react$/ }, () => ({
      path: path.resolve('./src/utils/icons.ts'),
    }))
  },
}

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    '@lexical/clipboard/clipboard',
    ...nodeBuiltins,
  ],
  format: 'cjs',
  // Map `node:events` (used by some deps) to the same polyfilled `events`
  // package so both forms resolve to a browser-compatible EventEmitter.
  alias: {
    'node:events': 'events',
  },
  inject: [path.resolve('import-meta-url-shim.js')],
  define: {
    'import.meta.url': 'import_meta_url',
    'process.env.NODE_ENV': JSON.stringify(prod ? 'production' : 'development'),
  },
  target: 'es2020',
  logLevel: 'info', // 'debug' for more detailed output
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  plugins: [pgliteShimPlugin, lucideIconsPlugin],
  outfile: 'main.js',
  minify: prod,
  metafile: true,
  plugins: [pgliteShimPlugin, lucideIconsPlugin],
})

if (prod) {
  const result = await context.rebuild()
  fs.writeFileSync('meta.json', JSON.stringify(result.metafile))
  process.exit(0)
} else {
  await context.watch()
}
